# Generated by Django 5.2.6 on 2025-10-31 09:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_author_remove_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/blog/', location='C:\\Users\\ADMIN\\Desktop\\Putsf-master2\\Putsf-master1\\Putsf-master\\Putsf\\server\\putsf_backend\\static\\blog'), upload_to=''),
        ),
    ]
