# Generated by Django 3.1.12 on 2025-11-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_remove_license_description_remove_license_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='license',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
